use_frameworks!
platform :ios

target 'Promise_swift_Example' do
  pod 'Promise.swift', :path => '../'

  target 'Promise_swift_Tests' do
    inherit! :search_paths

    pod 'PromisesSwift'
    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
#            if config == 'Testing'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
#            end
        end
    end
end
